# This workflow will install Python dependencies, run lint and other code checks
# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Code Checking

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  code-checking:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make
    - name: Install python DEV dependencies (no root)
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --only=dev --no-root
    - name: Linting
      run: make lint
    - name: Flaking
      run: make flake
    - name: Docstyle
      run: make docstyle
    - name: Blacking
      run: make black-check
